name: InfinityStaff
author: ["Atticus Zambrana"]
main: net.angusbeefgaming.staff.Core
version: 1.0
commands:
  freeze:
    description: Freeze a Player
  randomtp:
    description: Teleport to a Random player