name: InfinityStaff
author: ["Atticus Zambrana"]
main: net.angusbeefgaming.staff.Core
version: 1.0
commands:
  freeze:
    description: Freeze a Player
  randomtp:
    description: Teleport to a Random player
  sc:
    description: Communicate with other staff
  report:
    description: Report other players
  reviewreports:
    description: View all Unresolved Reports
  resolve:
    description: Resolve an Active Report